version: '3.8'

services:
  ## WORKER ##
  worker:
    container_name: calculator_worker
    build: ./DockerFiles/Worker
    ports:
      - ${SERVER_PORT}:80
      - ${REACT_PORT}:3000
    volumes:
      - ./var/log:/var/www/var/log
      - ./var/cache:/var/www/var/cache
      - .:/var/www:cached
volumes: {}